### ISSUE TITLE
Error while searching for peers for an unknown reason.

### ISSUE THREAD

**Issue by MedFehmiEBF** [Cheesebaron/WiFiDirectSample#1]
I just deployed to tow android devices with Android 10, as soon as I start the search for peers, the message "Discovery failed : Error" without further information.

**Comment by Cheesebaron** [comment]
Yeah, dunno what is up. I ported this code 7 years ago and I have no recollection of it. Sorry to say it, but you are on your own debugging this.

**Comment by MedFehmiEBF** [comment]
Thanks for the update, now it is working properly even I still don't know the reason for the error, but a question regarding the sample, theoretically speaking, would it be able to find any kind of device available on the network like windows 8/10 or each OS has his own API to work with?

**Comment by Cheesebaron** [comment]
@MedFehmiEBF only tested it with Android to Android connections. Read the Android docs 😄
